version: '3'

services:
  web:
    build: ./webapp
    ports:
      - "5000:5000"
         
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: teste_db
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
    ports:
      - "3307:3306"