"""empty message

Revision ID: bc350878c363
Revises: 9d1f7341f61f
Create Date: 2024-04-06 18:34:05.773491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc350878c363'
down_revision = '9d1f7341f61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instancia', schema=None) as batch_op:
        batch_op.alter_column('values',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instancia', schema=None) as batch_op:
        batch_op.alter_column('values',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
